apiVersion: v1
kind: Service
metadata:
  name:  argo-nginx-service
  labels:
    app.kubernetes.io/name: argo-nginx
spec:
  type: LoadBalancer
  selector:
    app:  nginx
  ports:
  - port:  80

    targetPort:  80
